// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: generated_itinerary.
// - Entity ID: 102019ac647147f74b8ab821b063e158051.
// - Entity Version: 102019ad31e8738725989b0fc9d913961e3.
// - Task ID: 692bce64a323fe2c2ea754ba.
// - Task Root ID: 692883ddc321cfaf0a53c7bc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for GeneratedItineraryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface GeneratedItineraryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  destination: string;
  start_date: string;
  end_date: string;
  days: string;
  total_estimated_cost: number;
  timestamp: string;
}

/**
 * ORM class for GeneratedItinerary entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class GeneratedItineraryORM {
  private static instance: GeneratedItineraryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac647147f74b8ab821b063e158051';
    this.entityName = 'generated_itinerary';
    this.entityVersion = '102019ad31e8738725989b0fc9d913961e3';
    this.taskId = '692bce64a323fe2c2ea754ba';
    this.taskRootId = '692883ddc321cfaf0a53c7bc';
  }

  /**
   * Get singleton instance of GeneratedItineraryORM
   */
  public static getInstance(): GeneratedItineraryORM {
    if (!GeneratedItineraryORM.instance) {
      GeneratedItineraryORM.instance = new GeneratedItineraryORM();
    }
    
    return GeneratedItineraryORM.instance;
  }

  /**
   * Get all GeneratedItinerary records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllGeneratedItinerary(): Promise<GeneratedItineraryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new GeneratedItinerary record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertGeneratedItinerary(data: GeneratedItineraryModel[]): Promise<GeneratedItineraryModel[]> {
    const structured = data.map((item) => CreateData(GeneratedItineraryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all GeneratedItinerary records
   */
  async purgeAllGeneratedItinerary(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List GeneratedItinerary records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listGeneratedItinerary(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[GeneratedItineraryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get generated_itinerary by Id index
   * This function gets data by index.
   */
  async getGeneratedItineraryById(
    id: string,
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) generated_itinerary by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGeneratedItineraryById(
    id: string,
    data: GeneratedItineraryModel
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexId(
      id
    );

    const values = GeneratedItineraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete generated_itinerary by Id index
   */
  async deleteGeneratedItineraryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get generated_itinerary by DataCreator index
   * This function gets data by index.
   */
  async getGeneratedItineraryByDataCreator(
    data_creator: string,
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) generated_itinerary by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGeneratedItineraryByDataCreator(
    data_creator: string,
    data: GeneratedItineraryModel
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = GeneratedItineraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete generated_itinerary by DataCreator index
   */
  async deleteGeneratedItineraryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get generated_itinerary by DataUpdater index
   * This function gets data by index.
   */
  async getGeneratedItineraryByDataUpdater(
    data_updater: string,
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) generated_itinerary by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGeneratedItineraryByDataUpdater(
    data_updater: string,
    data: GeneratedItineraryModel
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = GeneratedItineraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete generated_itinerary by DataUpdater index
   */
  async deleteGeneratedItineraryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get generated_itinerary by DataCreatorDestination index
   * This function gets data by index.
   */
  async getGeneratedItineraryByDataCreatorDestination(
    data_creator: string,
    destination: string,
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataCreatorDestination(
      data_creator,
      destination
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) generated_itinerary by DataCreatorDestination index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGeneratedItineraryByDataCreatorDestination(
    data_creator: string,
    destination: string,
    data: GeneratedItineraryModel
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataCreatorDestination(
      data_creator,
      destination
    );

    const values = GeneratedItineraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete generated_itinerary by DataCreatorDestination index
   */
  async deleteGeneratedItineraryByDataCreatorDestination(
    data_creator: string,
    destination: string
  ): Promise<void> {
    const index = createIndexDataCreatorDestination(
      data_creator,
      destination
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get generated_itinerary by DataCreatorTimestamp index
   * This function gets data by index.
   */
  async getGeneratedItineraryByDataCreatorTimestamp(
    data_creator: string,
    timestamp: string,
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataCreatorTimestamp(
      data_creator,
      timestamp
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) generated_itinerary by DataCreatorTimestamp index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGeneratedItineraryByDataCreatorTimestamp(
    data_creator: string,
    timestamp: string,
    data: GeneratedItineraryModel
  ): Promise<GeneratedItineraryModel[]> {
    const index = createIndexDataCreatorTimestamp(
      data_creator,
      timestamp
    );

    const values = GeneratedItineraryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete generated_itinerary by DataCreatorTimestamp index
   */
  async deleteGeneratedItineraryByDataCreatorTimestamp(
    data_creator: string,
    timestamp: string
  ): Promise<void> {
    const index = createIndexDataCreatorTimestamp(
      data_creator,
      timestamp
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to GeneratedItineraryModel data array
   */
  private resultToData(values: Data[]): GeneratedItineraryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return GeneratedItineraryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as GeneratedItineraryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized GeneratedItineraryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is GeneratedItineraryModel => item !== null);
  }
}

/**
 * Convert GeneratedItineraryModel data to Value array
 */
function GeneratedItineraryModelToValues(data: GeneratedItineraryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'destination', type: DataType.string, defaultValue: '' },
    { key: 'start_date', type: DataType.string, defaultValue: '' },
    { key: 'end_date', type: DataType.string, defaultValue: '' },
    { key: 'days', type: DataType.string, defaultValue: '' },
    { key: 'total_estimated_cost', type: DataType.number, defaultValue: 0 },
    { key: 'timestamp', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof GeneratedItineraryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to GeneratedItineraryModel data
 */
function GeneratedItineraryModelFromValues(values: Value[]): GeneratedItineraryModel {
  const data: Partial<GeneratedItineraryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'destination':
        data.destination = ParseValue(value, DataType.string) as string;
        break;
      case 'start_date':
        data.start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'end_date':
        data.end_date = ParseValue(value, DataType.string) as string;
        break;
      case 'days':
        data.days = ParseValue(value, DataType.string) as string;
        break;
      case 'total_estimated_cost':
        data.total_estimated_cost = ParseValue(value, DataType.number) as number;
        break;
      case 'timestamp':
        data.timestamp = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as GeneratedItineraryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for DataCreatorDestination fields
 */
function createIndexDataCreatorDestination(
  data_creator: string,
  destination: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.string, destination, 'destination'),
  ];

  return {
    fields: ['data_creator', 'destination'],
    values
  };
}
/**
 * Create index for DataCreatorTimestamp fields
 */
function createIndexDataCreatorTimestamp(
  data_creator: string,
  timestamp: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.string, timestamp, 'timestamp'),
  ];

  return {
    fields: ['data_creator', 'timestamp'],
    values
  };
}

export default GeneratedItineraryORM;