// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: preference_score.
// - Entity ID: 102019ac647147f795190c235b02970ab3f.
// - Entity Version: 102019ad31e8738725989b0fc9d913961e3.
// - Task ID: 692bce64a323fe2c2ea754ba.
// - Task Root ID: 692883ddc321cfaf0a53c7bc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for PreferenceScoreModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PreferenceScoreModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  tag_name: string;
  score: number;
}

/**
 * ORM class for PreferenceScore entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PreferenceScoreORM {
  private static instance: PreferenceScoreORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac647147f795190c235b02970ab3f';
    this.entityName = 'preference_score';
    this.entityVersion = '102019ad31e8738725989b0fc9d913961e3';
    this.taskId = '692bce64a323fe2c2ea754ba';
    this.taskRootId = '692883ddc321cfaf0a53c7bc';
  }

  /**
   * Get singleton instance of PreferenceScoreORM
   */
  public static getInstance(): PreferenceScoreORM {
    if (!PreferenceScoreORM.instance) {
      PreferenceScoreORM.instance = new PreferenceScoreORM();
    }
    
    return PreferenceScoreORM.instance;
  }

  /**
   * Get all PreferenceScore records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPreferenceScore(): Promise<PreferenceScoreModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PreferenceScore record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPreferenceScore(data: PreferenceScoreModel[]): Promise<PreferenceScoreModel[]> {
    const structured = data.map((item) => CreateData(PreferenceScoreModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PreferenceScore records
   */
  async purgeAllPreferenceScore(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PreferenceScore records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPreferenceScore(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PreferenceScoreModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get preference_score by Id index
   * This function gets data by index.
   */
  async getPreferenceScoreById(
    id: string,
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) preference_score by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPreferenceScoreById(
    id: string,
    data: PreferenceScoreModel
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexId(
      id
    );

    const values = PreferenceScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete preference_score by Id index
   */
  async deletePreferenceScoreById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get preference_score by DataCreator index
   * This function gets data by index.
   */
  async getPreferenceScoreByDataCreator(
    data_creator: string,
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) preference_score by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPreferenceScoreByDataCreator(
    data_creator: string,
    data: PreferenceScoreModel
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PreferenceScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete preference_score by DataCreator index
   */
  async deletePreferenceScoreByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get preference_score by DataUpdater index
   * This function gets data by index.
   */
  async getPreferenceScoreByDataUpdater(
    data_updater: string,
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) preference_score by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPreferenceScoreByDataUpdater(
    data_updater: string,
    data: PreferenceScoreModel
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PreferenceScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete preference_score by DataUpdater index
   */
  async deletePreferenceScoreByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get preference_score by DataCreatorTagName index
   * This function gets data by index.
   */
  async getPreferenceScoreByDataCreatorTagName(
    data_creator: string,
    tag_name: string,
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataCreatorTagName(
      data_creator,
      tag_name
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) preference_score by DataCreatorTagName index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPreferenceScoreByDataCreatorTagName(
    data_creator: string,
    tag_name: string,
    data: PreferenceScoreModel
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataCreatorTagName(
      data_creator,
      tag_name
    );

    const values = PreferenceScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete preference_score by DataCreatorTagName index
   */
  async deletePreferenceScoreByDataCreatorTagName(
    data_creator: string,
    tag_name: string
  ): Promise<void> {
    const index = createIndexDataCreatorTagName(
      data_creator,
      tag_name
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get preference_score by DataCreatorScore index
   * This function gets data by index.
   */
  async getPreferenceScoreByDataCreatorScore(
    data_creator: string,
    score: number,
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataCreatorScore(
      data_creator,
      score
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) preference_score by DataCreatorScore index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPreferenceScoreByDataCreatorScore(
    data_creator: string,
    score: number,
    data: PreferenceScoreModel
  ): Promise<PreferenceScoreModel[]> {
    const index = createIndexDataCreatorScore(
      data_creator,
      score
    );

    const values = PreferenceScoreModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete preference_score by DataCreatorScore index
   */
  async deletePreferenceScoreByDataCreatorScore(
    data_creator: string,
    score: number
  ): Promise<void> {
    const index = createIndexDataCreatorScore(
      data_creator,
      score
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PreferenceScoreModel data array
   */
  private resultToData(values: Data[]): PreferenceScoreModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PreferenceScoreModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PreferenceScoreModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PreferenceScoreModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PreferenceScoreModel => item !== null);
  }
}

/**
 * Convert PreferenceScoreModel data to Value array
 */
function PreferenceScoreModelToValues(data: PreferenceScoreModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'tag_name', type: DataType.string, defaultValue: '' },
    { key: 'score', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PreferenceScoreModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PreferenceScoreModel data
 */
function PreferenceScoreModelFromValues(values: Value[]): PreferenceScoreModel {
  const data: Partial<PreferenceScoreModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'tag_name':
        data.tag_name = ParseValue(value, DataType.string) as string;
        break;
      case 'score':
        data.score = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as PreferenceScoreModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for DataCreatorTagName fields
 */
function createIndexDataCreatorTagName(
  data_creator: string,
  tag_name: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.string, tag_name, 'tag_name'),
  ];

  return {
    fields: ['data_creator', 'tag_name'],
    values
  };
}
/**
 * Create index for DataCreatorScore fields
 */
function createIndexDataCreatorScore(
  data_creator: string,
  score: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.number, score, 'score'),
  ];

  return {
    fields: ['data_creator', 'score'],
    values
  };
}

export default PreferenceScoreORM;