// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: category_progress.
// - Entity ID: 102019ac647147f7824a6b679b53ae176b1.
// - Entity Version: 102019ad31e8738725989b0fc9d913961e3.
// - Task ID: 692bce64a323fe2c2ea754ba.
// - Task Root ID: 692883ddc321cfaf0a53c7bc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for CategoryProgressCategory
 */
export enum CategoryProgressCategory {
  Unspecified = 0,
  Locations = 1,
  Food = 2,
  Activities = 3,
  Accommodations = 4,
  Transportation = 5,
  Vibes = 6,
}



/**
 * Interface for CategoryProgressModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CategoryProgressModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  category: CategoryProgressCategory;
  swipe_count: number;
  is_complete: boolean;
}

/**
 * ORM class for CategoryProgress entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CategoryProgressORM {
  private static instance: CategoryProgressORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac647147f7824a6b679b53ae176b1';
    this.entityName = 'category_progress';
    this.entityVersion = '102019ad31e8738725989b0fc9d913961e3';
    this.taskId = '692bce64a323fe2c2ea754ba';
    this.taskRootId = '692883ddc321cfaf0a53c7bc';
  }

  /**
   * Get singleton instance of CategoryProgressORM
   */
  public static getInstance(): CategoryProgressORM {
    if (!CategoryProgressORM.instance) {
      CategoryProgressORM.instance = new CategoryProgressORM();
    }
    
    return CategoryProgressORM.instance;
  }

  /**
   * Get all CategoryProgress records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCategoryProgress(): Promise<CategoryProgressModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new CategoryProgress record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCategoryProgress(data: CategoryProgressModel[]): Promise<CategoryProgressModel[]> {
    const structured = data.map((item) => CreateData(CategoryProgressModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all CategoryProgress records
   */
  async purgeAllCategoryProgress(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List CategoryProgress records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCategoryProgress(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CategoryProgressModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get category_progress by Id index
   * This function gets data by index.
   */
  async getCategoryProgressById(
    id: string,
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) category_progress by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCategoryProgressById(
    id: string,
    data: CategoryProgressModel
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexId(
      id
    );

    const values = CategoryProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete category_progress by Id index
   */
  async deleteCategoryProgressById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get category_progress by DataCreator index
   * This function gets data by index.
   */
  async getCategoryProgressByDataCreator(
    data_creator: string,
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) category_progress by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCategoryProgressByDataCreator(
    data_creator: string,
    data: CategoryProgressModel
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CategoryProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete category_progress by DataCreator index
   */
  async deleteCategoryProgressByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get category_progress by DataUpdater index
   * This function gets data by index.
   */
  async getCategoryProgressByDataUpdater(
    data_updater: string,
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) category_progress by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCategoryProgressByDataUpdater(
    data_updater: string,
    data: CategoryProgressModel
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CategoryProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete category_progress by DataUpdater index
   */
  async deleteCategoryProgressByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get category_progress by CategoryDataCreator index
   * This function gets data by index.
   */
  async getCategoryProgressByCategoryDataCreator(
    category: CategoryProgressCategory,
    data_creator: string,
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexCategoryDataCreator(
      category,
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) category_progress by CategoryDataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCategoryProgressByCategoryDataCreator(
    category: CategoryProgressCategory,
    data_creator: string,
    data: CategoryProgressModel
  ): Promise<CategoryProgressModel[]> {
    const index = createIndexCategoryDataCreator(
      category,
      data_creator
    );

    const values = CategoryProgressModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete category_progress by CategoryDataCreator index
   */
  async deleteCategoryProgressByCategoryDataCreator(
    category: CategoryProgressCategory,
    data_creator: string
  ): Promise<void> {
    const index = createIndexCategoryDataCreator(
      category,
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CategoryProgressModel data array
   */
  private resultToData(values: Data[]): CategoryProgressModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CategoryProgressModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CategoryProgressModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CategoryProgressModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CategoryProgressModel => item !== null);
  }
}

/**
 * Convert CategoryProgressModel data to Value array
 */
function CategoryProgressModelToValues(data: CategoryProgressModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'swipe_count', type: DataType.number, defaultValue: 0 },
    { key: 'is_complete', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CategoryProgressModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CategoryProgressModel data
 */
function CategoryProgressModelFromValues(values: Value[]): CategoryProgressModel {
  const data: Partial<CategoryProgressModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as CategoryProgressCategory;
        break;
      case 'swipe_count':
        data.swipe_count = ParseValue(value, DataType.number) as number;
        break;
      case 'is_complete':
        data.is_complete = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as CategoryProgressModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for CategoryDataCreator fields
 */
function createIndexCategoryDataCreator(
  category: CategoryProgressCategory,
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, category, 'category'),
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['category', 'data_creator'],
    values
  };
}

export default CategoryProgressORM;