// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: swipe_history.
// - Entity ID: 102019ac647147f75feb9dede1620a38723.
// - Entity Version: 102019ad31e8738725989b0fc9d913961e3.
// - Task ID: 692bce64a323fe2c2ea754ba.
// - Task Root ID: 692883ddc321cfaf0a53c7bc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for SwipeHistoryCategory
 */
export enum SwipeHistoryCategory {
  Unspecified = 0,
  Locations = 1,
  Food = 2,
  Activities = 3,
  Accommodations = 4,
  Transportation = 5,
  Vibes = 6,
}
/**
 * Enumeration for SwipeHistoryDirection
 */
export enum SwipeHistoryDirection {
  Unspecified = 0,
  Right = 1,
  Left = 2,
}



/**
 * Interface for SwipeHistoryModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SwipeHistoryModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  card_id: string;
  category: SwipeHistoryCategory;
  direction: SwipeHistoryDirection;
  tags?: string[] | null;
  timestamp: string;
}

/**
 * ORM class for SwipeHistory entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SwipeHistoryORM {
  private static instance: SwipeHistoryORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac647147f75feb9dede1620a38723';
    this.entityName = 'swipe_history';
    this.entityVersion = '102019ad31e8738725989b0fc9d913961e3';
    this.taskId = '692bce64a323fe2c2ea754ba';
    this.taskRootId = '692883ddc321cfaf0a53c7bc';
  }

  /**
   * Get singleton instance of SwipeHistoryORM
   */
  public static getInstance(): SwipeHistoryORM {
    if (!SwipeHistoryORM.instance) {
      SwipeHistoryORM.instance = new SwipeHistoryORM();
    }
    
    return SwipeHistoryORM.instance;
  }

  /**
   * Get all SwipeHistory records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSwipeHistory(): Promise<SwipeHistoryModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SwipeHistory record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSwipeHistory(data: SwipeHistoryModel[]): Promise<SwipeHistoryModel[]> {
    const structured = data.map((item) => CreateData(SwipeHistoryModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SwipeHistory records
   */
  async purgeAllSwipeHistory(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SwipeHistory records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSwipeHistory(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SwipeHistoryModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get swipe_history by Id index
   * This function gets data by index.
   */
  async getSwipeHistoryById(
    id: string,
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) swipe_history by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSwipeHistoryById(
    id: string,
    data: SwipeHistoryModel
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexId(
      id
    );

    const values = SwipeHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete swipe_history by Id index
   */
  async deleteSwipeHistoryById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get swipe_history by DataCreator index
   * This function gets data by index.
   */
  async getSwipeHistoryByDataCreator(
    data_creator: string,
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) swipe_history by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSwipeHistoryByDataCreator(
    data_creator: string,
    data: SwipeHistoryModel
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SwipeHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete swipe_history by DataCreator index
   */
  async deleteSwipeHistoryByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get swipe_history by DataUpdater index
   * This function gets data by index.
   */
  async getSwipeHistoryByDataUpdater(
    data_updater: string,
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) swipe_history by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSwipeHistoryByDataUpdater(
    data_updater: string,
    data: SwipeHistoryModel
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SwipeHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete swipe_history by DataUpdater index
   */
  async deleteSwipeHistoryByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get swipe_history by CategoryDataCreator index
   * This function gets data by index.
   */
  async getSwipeHistoryByCategoryDataCreator(
    category: SwipeHistoryCategory,
    data_creator: string,
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexCategoryDataCreator(
      category,
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) swipe_history by CategoryDataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSwipeHistoryByCategoryDataCreator(
    category: SwipeHistoryCategory,
    data_creator: string,
    data: SwipeHistoryModel
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexCategoryDataCreator(
      category,
      data_creator
    );

    const values = SwipeHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete swipe_history by CategoryDataCreator index
   */
  async deleteSwipeHistoryByCategoryDataCreator(
    category: SwipeHistoryCategory,
    data_creator: string
  ): Promise<void> {
    const index = createIndexCategoryDataCreator(
      category,
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get swipe_history by DataCreatorTimestamp index
   * This function gets data by index.
   */
  async getSwipeHistoryByDataCreatorTimestamp(
    data_creator: string,
    timestamp: string,
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexDataCreatorTimestamp(
      data_creator,
      timestamp
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) swipe_history by DataCreatorTimestamp index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSwipeHistoryByDataCreatorTimestamp(
    data_creator: string,
    timestamp: string,
    data: SwipeHistoryModel
  ): Promise<SwipeHistoryModel[]> {
    const index = createIndexDataCreatorTimestamp(
      data_creator,
      timestamp
    );

    const values = SwipeHistoryModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete swipe_history by DataCreatorTimestamp index
   */
  async deleteSwipeHistoryByDataCreatorTimestamp(
    data_creator: string,
    timestamp: string
  ): Promise<void> {
    const index = createIndexDataCreatorTimestamp(
      data_creator,
      timestamp
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SwipeHistoryModel data array
   */
  private resultToData(values: Data[]): SwipeHistoryModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SwipeHistoryModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SwipeHistoryModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SwipeHistoryModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SwipeHistoryModel => item !== null);
  }
}

/**
 * Convert SwipeHistoryModel data to Value array
 */
function SwipeHistoryModelToValues(data: SwipeHistoryModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'card_id', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'direction', type: DataType.enumeration, defaultValue: 0 },
    { key: 'tags', type: DataType.array, defaultValue: null },
    { key: 'timestamp', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SwipeHistoryModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SwipeHistoryModel data
 */
function SwipeHistoryModelFromValues(values: Value[]): SwipeHistoryModel {
  const data: Partial<SwipeHistoryModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'card_id':
        data.card_id = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as SwipeHistoryCategory;
        break;
      case 'direction':
        data.direction = ParseValue(value, DataType.enumeration) as SwipeHistoryDirection;
        break;
      case 'tags':
        data.tags = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'timestamp':
        data.timestamp = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as SwipeHistoryModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for CategoryDataCreator fields
 */
function createIndexCategoryDataCreator(
  category: SwipeHistoryCategory,
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, category, 'category'),
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['category', 'data_creator'],
    values
  };
}
/**
 * Create index for DataCreatorTimestamp fields
 */
function createIndexDataCreatorTimestamp(
  data_creator: string,
  timestamp: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
    CreateValue(DataType.string, timestamp, 'timestamp'),
  ];

  return {
    fields: ['data_creator', 'timestamp'],
    values
  };
}

export default SwipeHistoryORM;