// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: questionnaire_response.
// - Entity ID: 102019ac647147f721d9b5ca13ac039e0c1.
// - Entity Version: 102019ad31e8738725989b0fc9d913961e3.
// - Task ID: 692bce64a323fe2c2ea754ba.
// - Task Root ID: 692883ddc321cfaf0a53c7bc.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for QuestionnaireResponseModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface QuestionnaireResponseModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  dietary_needs?: string[] | null;
  meal_budget?: string | null;
  food_adventurousness?: number | null;
  accommodation_type?: string[] | null;
  must_have_amenities?: string[] | null;
  price_per_night?: number | null;
  trip_start_date: string;
  trip_end_date: string;
  destination: string;
  number_of_travelers: number;
  total_budget?: number | null;
  timestamp: string;
}

/**
 * ORM class for QuestionnaireResponse entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class QuestionnaireResponseORM {
  private static instance: QuestionnaireResponseORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac647147f721d9b5ca13ac039e0c1';
    this.entityName = 'questionnaire_response';
    this.entityVersion = '102019ad31e8738725989b0fc9d913961e3';
    this.taskId = '692bce64a323fe2c2ea754ba';
    this.taskRootId = '692883ddc321cfaf0a53c7bc';
  }

  /**
   * Get singleton instance of QuestionnaireResponseORM
   */
  public static getInstance(): QuestionnaireResponseORM {
    if (!QuestionnaireResponseORM.instance) {
      QuestionnaireResponseORM.instance = new QuestionnaireResponseORM();
    }
    
    return QuestionnaireResponseORM.instance;
  }

  /**
   * Get all QuestionnaireResponse records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllQuestionnaireResponse(): Promise<QuestionnaireResponseModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new QuestionnaireResponse record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertQuestionnaireResponse(data: QuestionnaireResponseModel[]): Promise<QuestionnaireResponseModel[]> {
    const structured = data.map((item) => CreateData(QuestionnaireResponseModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all QuestionnaireResponse records
   */
  async purgeAllQuestionnaireResponse(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List QuestionnaireResponse records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listQuestionnaireResponse(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[QuestionnaireResponseModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get questionnaire_response by Id index
   * This function gets data by index.
   */
  async getQuestionnaireResponseById(
    id: string,
  ): Promise<QuestionnaireResponseModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questionnaire_response by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionnaireResponseById(
    id: string,
    data: QuestionnaireResponseModel
  ): Promise<QuestionnaireResponseModel[]> {
    const index = createIndexId(
      id
    );

    const values = QuestionnaireResponseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questionnaire_response by Id index
   */
  async deleteQuestionnaireResponseById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get questionnaire_response by DataCreator index
   * This function gets data by index.
   */
  async getQuestionnaireResponseByDataCreator(
    data_creator: string,
  ): Promise<QuestionnaireResponseModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questionnaire_response by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionnaireResponseByDataCreator(
    data_creator: string,
    data: QuestionnaireResponseModel
  ): Promise<QuestionnaireResponseModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = QuestionnaireResponseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questionnaire_response by DataCreator index
   */
  async deleteQuestionnaireResponseByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get questionnaire_response by DataUpdater index
   * This function gets data by index.
   */
  async getQuestionnaireResponseByDataUpdater(
    data_updater: string,
  ): Promise<QuestionnaireResponseModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) questionnaire_response by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setQuestionnaireResponseByDataUpdater(
    data_updater: string,
    data: QuestionnaireResponseModel
  ): Promise<QuestionnaireResponseModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = QuestionnaireResponseModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete questionnaire_response by DataUpdater index
   */
  async deleteQuestionnaireResponseByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to QuestionnaireResponseModel data array
   */
  private resultToData(values: Data[]): QuestionnaireResponseModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return QuestionnaireResponseModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as QuestionnaireResponseModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized QuestionnaireResponseModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is QuestionnaireResponseModel => item !== null);
  }
}

/**
 * Convert QuestionnaireResponseModel data to Value array
 */
function QuestionnaireResponseModelToValues(data: QuestionnaireResponseModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'dietary_needs', type: DataType.array, defaultValue: null },
    { key: 'meal_budget', type: DataType.string, defaultValue: null },
    { key: 'food_adventurousness', type: DataType.number, defaultValue: null },
    { key: 'accommodation_type', type: DataType.array, defaultValue: null },
    { key: 'must_have_amenities', type: DataType.array, defaultValue: null },
    { key: 'price_per_night', type: DataType.number, defaultValue: null },
    { key: 'trip_start_date', type: DataType.string, defaultValue: '' },
    { key: 'trip_end_date', type: DataType.string, defaultValue: '' },
    { key: 'destination', type: DataType.string, defaultValue: '' },
    { key: 'number_of_travelers', type: DataType.number, defaultValue: 0 },
    { key: 'total_budget', type: DataType.number, defaultValue: null },
    { key: 'timestamp', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof QuestionnaireResponseModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to QuestionnaireResponseModel data
 */
function QuestionnaireResponseModelFromValues(values: Value[]): QuestionnaireResponseModel {
  const data: Partial<QuestionnaireResponseModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'dietary_needs':
        data.dietary_needs = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'meal_budget':
        data.meal_budget = ParseValue(value, DataType.string) as string | null;
        break;
      case 'food_adventurousness':
        data.food_adventurousness = ParseValue(value, DataType.number) as number | null;
        break;
      case 'accommodation_type':
        data.accommodation_type = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'must_have_amenities':
        data.must_have_amenities = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'price_per_night':
        data.price_per_night = ParseValue(value, DataType.number) as number | null;
        break;
      case 'trip_start_date':
        data.trip_start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'trip_end_date':
        data.trip_end_date = ParseValue(value, DataType.string) as string;
        break;
      case 'destination':
        data.destination = ParseValue(value, DataType.string) as string;
        break;
      case 'number_of_travelers':
        data.number_of_travelers = ParseValue(value, DataType.number) as number;
        break;
      case 'total_budget':
        data.total_budget = ParseValue(value, DataType.number) as number | null;
        break;
      case 'timestamp':
        data.timestamp = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as QuestionnaireResponseModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default QuestionnaireResponseORM;